//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
//
#include <cstdio>
#include <cmath>
#include<iostream>

int fibo(int a);
int sum(int a);

int main (void){
	std::cout<<fibo(33)<<std::endl;
//	printf(fibo(4000000));i
	std::cout<<sum(35)<<std::endl;
	return 0;
}


int fibo(int a){
	if (a==0 or a==1){
		return 1;
	}
	else return fibo(a-2)+fibo(a-1);
}



int sum(int a){
	int kk=0;
	for (int ii=2;ii<=a;++ii) if (fibo(ii)%2==0 && fibo(ii)<4000000){
		kk=kk+fibo(ii);
	}
	return kk;
}

